package nro;

import nro.nr_bo;
import nro.nr_bv;
import nro.Res;
import nro.Main;
import nro.nr_x;

public class mResources {

   public static String a = "";
   public static String b = "";
   public static String c = "";
   public static String d = "";
   public static String e = "";
   public static String f = "";
   public static String g = "";
   public static String h = "";
   public static String i;
   public static String j;
   public static String k;
   public static String l;
   public static String m;
   public static String n;
   public static String o;
   public static String p;
   public static String q;
   public static String r;
   public static String s;
   public static String t;
   public static String u;
   public static String v;
   public static String w;
   public static String x;
   public static String y;
   public static String z = "";
   public static String A;
   public static String B;
   public static String C;
   public static String D;
   public static String E = "";
   public static String F = "";
   public static String G = "";
   public static String H = "";
   public static String I = "";
   public static String J = "";
   public static String K = "";
   public static String L = "";
   public static String M = "";
   public static String N = "";
   public static String O = "";
   public static String P = "";
   public static String Q = "";
   public static String R = "";
   public static String S = "";
   public static String T = "";
   public static String U = "";
   public static String V = "";
   public static String W = "";
   public static String X = "";
   public static String Y = "";
   public static String Z;
   public static String[] aa;
   public static String ab;
   public static String ac;
   public static String ad;
   public static String ae;
   public static String af;
   public static String ag;
   public static String ah;
   public static String ai;
   public static String aj;
   public static String ak;
   public static String al;
   public static String am;
   public static String an;
   public static String ao;
   public static String ap;
   public static String aq;
   public static String ar;
   public static String as;
   public static String at;
   public static String au;
   public static String av;
   public static String aw;
   public static String ax;
   public static String ay;
   public static String az;
   public static String aA;
   public static String aB;
   public static String aC;
   public static String aD;
   public static String aE;
   public static String aF;
   public static String[] aG;
   public static String[] aH;
   public static String[] aI;
   public static String[][] aJ;
   public static String[][] aK;
   public static String[][] aL;
   public static String[][] aM;
   public static String[] aN;
   public static String[] aO;
   public static String aP;
   public static String aQ;
   public static String aR;
   public static String[] aS;
   public static String[] aT;
   public static String[] aU;
   public static String aV;
   public static String aW;
   public static String aX;
   public static String aY;
   public static String aZ;
   public static String ba;
   public static String bb;
   public static String bc;
   public static String bd;
   public static String be;
   public static String bf;
   public static String bg;
   public static String bh;
   public static String bi;
   public static String bj;
   public static String bk;
   public static String bl;
   public static String bm;
   public static String bn;
   public static String bo;
   public static String bp;
   public static String bq;
   public static String br;
   public static String bs;
   public static String bt;
   public static String bu;
   public static String bv;
   public static String bw;
   public static String bx;
   public static String by;
   public static String bz;
   public static String bA;
   public static String bB;
   public static String bC;
   public static String bD;
   public static String bE;
   public static String bF;
   public static String bG;
   public static String bH;
   public static String bI;
   public static String bJ;
   public static String bK;
   public static String bL;
   public static String bM;
   public static String bN;
   public static String bO;
   public static String bP;
   public static String bQ;
   public static String bR;
   public static String bS;
   public static String bT;
   public static String bU;
   public static String bV;
   public static String bW;
   public static String bX;
   public static String bY;
   public static String bZ;
   public static String[] ca;
   public static String[] cb;
   public static String[] cc;
   public static String[] cd;
   public static String[] ce;
   public static String[] cf;
   public static String[] cg;
   public static String ch;
   public static String ci;
   public static String cj;
   public static String ck;
   public static String cl;
   public static String cm;
   public static String cn;
   public static String co;
   public static String cp;
   public static String cq;
   public static String cr;
   public static String cs;
   public static String ct;
   public static String cu;
   public static String cv;
   public static String cw;
   public static String cx;
   public static String cy;
   public static String cz;
   public static String cA;
   public static String cB;
   public static String cC;
   public static String cD;
   public static String cE;
   public static String cF;
   public static String cG;
   public static String cH;
   public static String plsRestartGame;
   public static String cJ;
   public static String cK;
   public static String cL;
   public static String cM;
   public static String cN;
   public static String cO;
   public static String cP;
   public static String cQ;
   public static String cR;
   public static String cS;
   public static String cT;
   public static String cU;
   public static String cV;
   public static String cW;
   public static String cX;
   public static String cY;
   public static String cZ;
   public static String da;
   public static String db;
   public static String[] dc;
   public static String[] dd;
   public static String[] de;
   public static String[] df;
   public static String[] dg;
   public static String[] dh;
   public static String[] di;
   public static String[] dj;
   public static String dk;
   public static String dl;
   public static String dm;
   public static String dn;
   public static String[] fd_array_2;
   public static String dp;
   public static String dq;
   public static String dr;
   public static String ds;
   public static String dt;
   public static String du;
   public static String dv;
   public static String dw;
   public static String dx;
   public static String dy;
   public static String dz;
   public static String dA;
   public static String dB;
   public static String dC;
   public static String dD;
   public static String dE;
   public static String dF;
   public static String dG;
   public static String dH;
   public static String dI;
   public static String dJ;
   public static String dK;
   public static String dL;
   public static String dM;
   public static String dN;
   public static String dO;
   public static String dP;
   public static String dQ;
   public static String dR;
   public static String dS;
   public static String dT;
   public static String dU;
   public static String dV;
   public static String dW;
   public static String dX;
   public static String dY;
   public static String dZ;
   public static String ea;
   public static String eb;
   public static String ec;
   public static String ed;
   public static String ee;
   public static String ef;
   public static String eg;
   public static String eh;
   public static String ei;
   public static String ej;
   public static String ek;
   public static String el;
   public static String em;
   public static String en;
   public static String eo;
   public static String ep;
   public static String eq;
   public static String er;
   public static String es;
   public static String et;
   public static String eu;
   public static String ev;
   public static String ew;
   public static String ex;
   public static String ey;
   public static String ez;
   public static String eA;
   public static String eB;
   public static String eC;
   public static String eD;
   public static String eE;
   public static String eF;
   public static String eG;
   public static String eH;
   public static String eI;
   public static String eJ;
   public static String eK;
   public static String eL;
   public static String eM;
   public static String eN;
   public static String eO;
   public static String eP;
   public static String eQ;
   public static String eR;
   public static String eS;
   public static String eT;
   public static String eU;
   public static String eV;
   public static String eW;
   public static String eX;
   public static String eY;
   public static String eZ;
   public static String fa;
   public static String fb;
   public static String fc;
   public static String fd;
   public static String fe;
   public static String ff;
   public static String fg;
   public static String fh;
   public static String fi;
   public static String fj;
   public static String[][] fk;
   public static String fl;
   public static String fm;
   public static String fn;
   public static String fo;
   public static String fp;
   public static String fq;
   public static String fr;
   public static String fs;
   public static String ft;
   public static String fu;
   public static String fv;
   public static byte fw;
   public static String fx;
   public static String fy;
   public static String fz;
   public static String fA;
   public static String fB;
   public static String fC;
   public static String fD;
   public static String fE;
   public static String fF;
   public static String fG;
   public static String fH;
   public static String fI;
   public static String fJ;
   public static String fK;
   public static String fL;
   public static String fM;
   public static String fN;
   public static String fO;
   public static String fP;
   public static String fQ;
   public static String fR;
   public static String fS;
   public static String fT;
   public static String fU;
   public static String fV;
   public static String fW;
   public static String fX;
   public static String fY;
   public static String fZ;
   public static String ga;
   public static String gb;
   public static String gc;
   public static String gd;
   public static String ge;
   public static String gf;
   public static String gg;
   public static String gh;
   public static String gi;


   static {
      String[] var10000 = new String[]{"", ""};
      Z = "";
      aa = new String[]{"", ""};
      ab = "";
      ac = "";
      ad = "";
      ae = "";
      af = "";
      ag = "";
      ah = "";
      ai = "";
      aj = "";
      ak = "";
      al = "";
      am = "";
      an = "";
      ao = "";
      ap = "";
      aq = "";
      ar = "";
      as = "";
      at = "";
      au = "";
      av = "";
      aw = "";
      ax = "";
      ay = "";
      az = "";
      aA = "";
      aB = "";
      aC = "";
      aD = "";
      aE = "";
      aF = "";
      var10000 = new String[]{"", "", "", "", ""};
      aG = new String[]{"", "", ""};
      aH = new String[]{"", "", ""};
      aI = new String[]{"", "", "", "", "", "", "", "", "", ""};
      aJ = new String[][]{{"", ""}, {"", ""}, {"", ""}, {"", ""}};
      aK = new String[][]{{"", ""}, {"", ""}, {"", ""}, {"", ""}, {"", ""}};
      aL = new String[][]{{"", ""}, {"", ""}};
      aM = new String[][]{{"", ""}};
      aN = new String[]{"", "", "", "", "", "", "", "", "", ""};
      aO = new String[]{"", "", "", "", "", "", "", "", "", ""};
      aP = "";
      aQ = "";
      aR = "";
      aS = new String[]{" ", "", "", ""};
      aT = new String[]{"", "", "", ""};
      var10000 = new String[]{"", "", ""};
      aU = new String[]{"", "", "", "", "", "", "", "", "", "", "", ""};
      aV = "";
      aW = "";
      aX = "";
      aY = "";
      aZ = "";
      ba = "";
      bb = "";
      bc = "";
      bd = "";
      be = "";
      bf = "";
      bg = "";
      bh = "";
      bi = "";
      bj = "";
      bk = "";
      bl = "";
      bm = "";
      bn = "";
      bo = "";
      bp = "";
      bq = "";
      br = "";
      bs = "";
      bt = "";
      bu = "";
      bv = "";
      bw = "";
      bx = "";
      by = "";
      bz = "";
      bA = "";
      bB = "";
      bC = "";
      bD = "";
      bE = "";
      bF = "";
      bG = "";
      bH = "";
      bI = "";
      bJ = "";
      bK = "";
      bL = "";
      bM = "";
      bN = "";
      bO = "";
      bP = "";
      bQ = "";
      bR = "";
      bS = "";
      bT = "";
      bU = "";
      bV = "";
      bW = "";
      bX = "";
      bY = "";
      bZ = "";
      ca = new String[]{"", ""};
      cb = new String[]{"", ""};
      cc = new String[]{"", ""};
      cd = new String[]{"", ""};
      ce = new String[]{"", ""};
      cf = new String[]{"", ""};
      cg = new String[]{"", ""};
      ch = "";
      ci = "";
      cj = "";
      ck = "";
      cl = "";
      cm = "";
      cn = "";
      co = "";
      cp = "";
      cq = "";
      cr = "";
      cs = "";
      ct = "";
      cu = "";
      cv = "";
      cw = "";
      cx = "";
      cy = "";
      cz = "";
      cA = "";
      cB = "";
      cC = "";
      cD = "";
      cE = "";
      cF = "";
      cG = "";
      cH = "";
      plsRestartGame = "";
      cJ = "";
      cK = "";
      cL = "";
      cM = "";
      cN = "";
      cO = "";
      cP = "";
      cQ = "";
      cR = "";
      cS = "";
      cT = "";
      cU = "";
      cV = "";
      cW = "";
      cX = "";
      cY = "";
      cZ = "";
      da = "";
      db = "";
      dc = new String[]{"", ""};
      dd = new String[]{"", ""};
      de = new String[]{"", ""};
      df = new String[]{"", ""};
      dg = new String[]{"", ""};
      dh = new String[]{""};
      di = new String[]{""};
      dj = new String[]{"", ""};
      dk = "";
      dl = "";
      dm = "";
      dn = "";
      fd_array_2 = new String[]{"", "", "", "", ""};
      dp = "";
      dq = "";
      dr = "";
      ds = "";
      dt = "";
      du = "";
      dv = "";
      dw = "";
      dx = "";
      dy = "";
      dz = "";
      dA = "";
      dB = "";
      dC = "";
      dD = "";
      dE = "";
      dF = "";
      dG = "";
      dH = "";
      dI = "";
      dJ = "";
      dK = "";
      dL = "";
      dM = "";
      dN = "";
      dO = "";
      dP = "";
      dQ = "";
      dR = "";
      dS = "";
      dT = "";
      dU = "";
      dV = "";
      dW = "";
      dX = "";
      dY = "";
      dZ = "";
      ea = "";
      eb = "";
      ec = "";
      ed = "";
      ee = "";
      ef = "";
      eg = "";
      eh = "";
      ei = "";
      ej = "";
      ek = "";
      el = "";
      em = "";
      en = "";
      eo = "";
      ep = "";
      eq = "";
      er = "";
      es = "";
      et = "";
      eu = "";
      ev = "";
      ew = "";
      ex = "";
      ey = "";
      ez = "";
      eA = "";
      eB = "";
      eC = "";
      eD = "";
      eE = "";
      eF = "";
      eG = "";
      eH = "";
      eI = "";
      eJ = "";
      eK = "";
      eL = "";
      eM = "";
      eN = "";
      eO = "";
      eP = "";
      eQ = "";
      eR = "";
      eS = "";
      eT = "";
      eU = "";
      eV = "";
      eW = "";
      eX = "";
      eY = "";
      eZ = "";
      fa = "";
      fb = "";
      fc = "";
      fd = "";
      fe = "";
      ff = "";
      fg = "";
      fh = "";
      fi = "";
      fj = "";
      fk = new String[][]{{"", "", ""}, {"", "", ""}, {"", "", ""}};
      fl = "";
      fm = "";
      fn = "";
      fo = "";
      fp = "";
      fq = "";
      fr = "";
      fs = "";
      ft = "";
      fu = "";
      fv = "";
      fz = "";
      fU = "";
      gf = "";
      a((byte)1);
   }

   public static void a(byte var0) {
      Res.out("LOAD LANGUAGE " + var0);
      fw = var0;
      String[] var10000;
      switch(var0) {
      case 0:
         nr_bo.j = "http://nrosuno.com/";
         nr_x.j = Main.loadImage("/mainImage/logo1.png");
         a = "Xóa tài khoản";
         b = "Hôm nay bạn đã nạp nhiều ngọc. Ngày mai hãy nạp tiếp nhé!";
         c = "Khi bán thành công sẽ nhận lại Hồng Ngọc không phải Ngọc, bạn có muốn tiếp tục kí gửi?";
         d = "Sử dụng";
         e = "Mở khóa";
         f = "Sổ sưu tầm";
         g = "Bạn không đủ";
         h = "Chức năng tạm dừng để bảo trì";
         z = "Nạp Ngọc";
         av = "Bạn có chắc muốn nhặt vật phẩm này không ?";
         i = "tầng";
         j = "Con số may mắn";
         bP = "Mini game";
         bO = "Thông báo";
         k = "Tự động hồi sinh";
         l = "Chức năng auto";
         m = "Bạn có chắc muốn kết hợp vĩnh viễn với đệ tử của mình không? Bạn sẽ mất đệ tử và toàn bộ trang bị đệ tử đang mặc, toàn bộ sức mạnh của đệ tử sẽ chuyển thành tiềm năng của bạn";
         gh = "Hợp thể vĩnh viễn";
         gg = "Hợp thể";
         ge = "Vui lòng nhập đủ thông tin";
         n = "Chơi tiếp";
         s = "Về nhà";
         r = "Trạng thái";
         o = "Tấn công";
         p = "Bảo vệ";
         q = "Đi theo";
         t = "Đệ tử";
         u = "Máy chủ tắt hoặc mất sóng";
         v = "Cấu hình thấp";
         w = "Cấu hình cao";
         fZ = "Tải dữ liệu";
         ga = "Xóa dữ liệu";
         gb = "Bạn cần xóa trong trường hợp có lỗi tải dữ liệu. Khi xóa xong, bạn phải tải lại toàn bộ để có thể chơi.";
         fY = "Hủy";
         fX = "Vui lòng tải dữ liệu để chơi";
         x = "Úm ba la xì bùa...";
         A = "Chúc mừng con nhé";
         y = "Chúc con may mắn lần sau";
         fW = "Bạn có đến tương lai ngay bây giờ với giá 1 ngọc không ?";
         fV = "Tăng tốc";
         B = "Bàn phím ảo";
         C = "Bàn phím ảo";
         D = "Bàn phím ảo";
         fS = "Mã bảo vệ";
         fT = "Nhập mã bảo vệ";
         fU = "Mã bảo vệ phải có độ dài là 6 số.";
         fR = "Vui lòng nhập số điện thoại hoặc địa chỉ email,sau đó nhập mật khẩu để tạo tài khoản mới";
         fQ = "Bạn sẽ mất tài khoản đang chơi và không thể khôi phục được nếu đổi tài khoản khác, bạn có đồng ý không ?";
         E = "Đăng kí để bảo vệ tài khoản";
         fP = "Bạn phải hoàn thành nhiệm vụ tìm ngọc 6 sao mới có thể nạp tiền";
         fO = "Diễn đàn và Nạp Ngọc";
         fN = "Chưa có vật phẩm rao bán";
         fM = "Kéo lên để cập nhật thêm";
         fL = "Kéo xuống để cập nhật thêm";
         fK = "Trang";
         fJ = "Up Top";
         fB = "Bán bằng\nvàng";
         fC = "Bán bằng\nngọc";
         fD = "Bán bằng vàng";
         fE = "Bán bằng ngọc";
         fF = "Hủy\nkí gửi";
         fG = "Nhận tiền";
         fI = "Đã bán";
         fH = "Đang bán";
         fA = "Kí gửi";
         fx = "Âm thanh";
         fy = "Âm thanh";
         bH = "Hạng";
         bI = "Năng động";
         F = "Đang đăng ký";
         G = "Đã gửi tin nhắn, xin chờ tin nhắn xác nhận.";
         H = "Không thể gởi tin nhắn. Xin kiểm tra tiền và thử khởi động lại game.";
         I = "Gửi tin nhắn thành công";
         J = "Không thể gửi tin nhắn";
         K = "Chúc mừng bạn đã gởi tin nhắn dự đoán thành công.";
         L = "Tin nhắn gửi không thành công.";
         M = "Mật khẩu phải có độ dài là 6 ký tự.";
         N = "Mật khẩu bảo vệ chỉ cho nhập số.";
         O = "Nhập mật khẩu bảo vệ";
         P = "Đổi tài khoản";
         Q = "Bạn chưa nhập email hoặc số di động.";
         R = "Bạn chưa nhập mật khẩu";
         S = "Tên tài khoản phải nhiều hơn 5 ký tự";
         T = "Số di động không hợp lệ. Xin nhập theo mẫu 0912345678 hoặc 84918765432";
         U = "Email không hợp lệ. Xin nhập theo mẫu tencuaban@yahoo.com hoặc tencuaban@gmail.com";
         V = "Đăng ký\ntài khoản\nmới";
         W = "Chọn\nmáy chủ";
         X = "Quên M.khầu";
         Y = "Mật khẩu";
         var10000 = new String[]{"Chưa có tài khoản xin", "chọn menu đăng ký."};
         Z = "Tin nhắn";
         aa = new String[]{"Tin", "nhắn"};
         ab = "Không có tin nhắn";
         ac = "Bạn có muốn huỷ chức năng bảo vệ tài khoản không ?";
         ad = "Kiểm tra chính xác để lấy lại được tài khoản nếu sau này quên mật khẩu\n";
         ae = "Số di động";
         af = "Địa chỉ mail";
         ag = "TK";
         ah = "MK";
         ai = "Để lấy lại mật khẩu, xin vui lòng vào website http://nrosuno.com/matkhau";
         aj = "Ngọc rồng";
         ak = "Nhân vật";
         al = "Tài khoản";
         am = "Tài khoản máy chủ";
         an = "Bạn chưa nhập tên nhân vật";
         ao = "Tên nhân vật quá ngắn";
         ap = "Tên nhân vật không được quá 15 kí tự";
         aq = "Nhân vật cần đổi tên";
         ar = "Tên nhân vật";
         as = "Đăng nhập";
         at = "Đ.Nhập";
         au = "Đăng ký";
         gi = "Dịch \nchuyển tới";
         bn = "Trả thù";
         aw = "Xin chờ";
         ax = "Đang kết nối";
         fz = "Không có kẻ thù";
         ay = "Đang tải ";
         az = "Có lỗi xảy ra, xin vui lòng khởi động lại game.";
         aA = "Có lỗi xảy ra.";
         aB = "Mất kết nối với máy chủ ";
         aC = "Đổi khu vực";
         aD = "Chọn khu vực";
         aE = "Website\ndiễn đàn";
         aF = "Máy chủ";
         var10000 = new String[]{"Hành trang", "Kỹ năng", "Tiềm năng", "Thông tin", "Trang bị"};
         aG = new String[]{"", "Dân tộc: ", "Tóc: "};
         aH = new String[]{"Trái đất", "Namếc", "Xayda"};
         if(Main.typeClient == 7) {
            aH = new String[]{"Rồng đất", "Rồng xanh", "Rồng đỏ"};
         }

         aI = new String[]{"Thách đấu", "Luyện tập", "Cừu sát", "Kết bạn", "Mời vào bang", "Phục hồi", "Xem thông tin", "Chat riêng", "Mời vào tộc", "Chặn xin vào tộc"};
         aJ = new String[][]{{"Nhiệm", "Vụ"}, {"Hành", "Trang"}, {"Kỹ", "Năng"}, {"Chức", "Năng"}};
         aK = new String[][]{{"Nhiệm", "Vụ"}, {"Hành", "Trang"}, {"Kỹ", "Năng"}, {"Bang", "Hội"}, {"Chức", "Năng"}};
         aL = new String[][]{{"Đệ", "Tử"}, {"Trạng", "Thái"}, {"Hành", "Trang"}};
         aM = new String[][]{{"Đệ", "Tử"}, {"Trạng", "Thái"}};
         aN = new String[]{"Vào\nphím Q", "Vào\nphím W", "Vào\nphím E", "Vào\nphím R", "Vào\nphím T", "", "", "", "", ""};
         aO = new String[]{"Vào\nphím 7", "Vào\nphím 8", "Vào\nphím 9", "Vào\nphím 1", "Vào\nphím 3", "", "", "", "", ""};
         aP = "Chiêu đánh hiện tại của bạn chưa nâng cấp độ";
         aQ = "Đã hết đậu thần. Cậu hãy về thu hoạch thêm";
         aR = "Bạn đang ở khu vực này";
         aS = new String[]{"Hãy đi tìm ", " ở ", " để nhận nhiệm vụ.", "Bạn đã hoàn thành hết nhiệm vụ phiên bản này, vui lòng chờ cho đến khi ra phiên bản tiếp theo."};
         aT = new String[]{"Kiệt sức", "Chờ", "Về nhà", "Hồi sinh\nngay\n(1 ngọc)"};
         var10000 = new String[]{"Bản đồ", "Nhiệm vụ", "Gia tộc"};
         aU = new String[]{"Đậu thần dùng để tăng KI và HP ngay lập tức", "Bạn chỉ mang theo người được 10 hạt đậu. Nếu muốn mang nhiều hơn, hãy xin từ bạn bè trong Bang", "Tất cả các sách kỹ năng đều có thể học miễn phí tại Quy Lão Kame, khi bạn có đủ điểm tiềm năng", "Bạn không thể bay, dùng kỹ năng, nếu hết KI", "Tấn công quái vật cùng bạn bè trong Bang sẽ mang lại nhiều điểm tiềm năng hơn đánh một mình", "Tập luyện với bạn bè tại khu vực thích hợp sẽ mang lại nhiều điểm tiềm năng hơn đánh quái vật", "Khi được nâng cấp, đậu thần sẽ phục hồi nhiều HP và KI hơn", "Vào trò chơi đều đặn mỗi ngày để nhận được Ngọc miễn phí", "Đùi gà sẽ phục hồi 100% HP, KI. Cà chua phục hồi 100% KI. Cà rốt phục hồi 100% HP", "Cây đậu thần kết một hạt sau một thời gian, cho dù bạn đang offline", "Sau 3 ngày không tham gia trò chơi, bạn sẽ bị giảm sức mạnh do lười luyện tập", "Bạn sẽ giảm thể lực khi đánh quái, nhưng sẽ tăng lại thể lực khi không đánh nữa", "Khi nào hết ngọc, bạn hãy đến chỗ Bò Mộng"};
         aV = "Sau khi gia nhập vào lớp học, thì có thể nhận nhiệm vụ từ hiệu trưởng";
         aW = "Số seri";
         aX = "Mã thẻ";
         aY = "Nạp thẻ Vina, Mobi, Viettel, Gate";
         aZ = "Nạp thẻ";
         ba = "Vui lòng nhập số serial";
         bb = "Vui lòng nhập mã code";
         bc = "Tỉ";
         bd = "Tr";
         be = "Menu";
         bf = "Đóng";
         bg = "Xóa";
         bh = "Tiếp tục";
         bi = "Sử dụng";
         bj = "Có";
         bk = "Không";
         bl = "Thoát";
         bm = "Chat";
         bo = "OK";
         bp = "Nhớ";
         bq = "Đồng ý";
         br = "Hủy";
         bs = "Chọn";
         bt = "Đi vào";
         bu = "Mở link";
         bv = "Tạo mới";
         bw = "Đóng";
         bx = "Tiêu diệt";
         by = "Bắt tà thú";
         bz = "vàng";
         bA = "ngọc";
         bB = "hồng ngọc";
         bC = "Điểm hiếu chiến của bạn hiện tại là ";
         bD = " bắt đầu cừu sát bạn";
         bE = "Không đủ KI để sử dụng";
         bF = "Bạn nhận được";
         bG = "Bạn học được ";
         bJ = "Bạn bè";
         bK = "Kẻ thù";
         bL = "Không có bạn bè";
         bM = "Chat thế giới";
         bN = "Đổi cờ";
         bQ = "Cấu hình";
         bR = "Tăng đồ họa (cho máy mạnh)";
         bS = "Giảm đồ họa (cho máy yếu)";
         bT = "Thông báo từ máy chủ";
         bX = "Hào quang đặc biệt";
         bY = "Hào quang sức mạnh";
         bU = "Màn hình lớn";
         bV = "Màn hình nhỏ";
         bW = "Bạn có muốn thoát game để thay đổi cỡ màn hình không ?";
         bZ = "Rương đồ";
         ca = new String[]{"Rương", "Đồ"};
         cb = new String[]{"Hành", "Trang"};
         cc = new String[]{"Kết", "hợp"};
         cd = new String[]{"Bản", "đồ"};
         ce = new String[]{"Item", "cho"};
         cf = new String[]{"Item", "nhận"};
         cg = new String[]{"Khu", "Vực"};
         ch = "Khu vực";
         ci = "Bản đồ";
         cj = "Item nhận";
         ck = "Nhận";
         cl = "Nhận tất";
         cm = "Hãy đến vị trí chớp nháy trên bản đồ để làm nhiệm vụ";
         cn = "Dành cho Trái Đất\n";
         co = "Dành cho Namếc\n";
         cp = "Dành cho Xayda\n";
         cq = "Sức mạnh yêu cầu";
         cr = "Sức mạnh của bạn";
         cs = "Đã dùng";
         ct = "ô";
         cu = "Nâng cấp";
         cv = "Đang nâng cấp";
         cw = "Gán ô\nphím tắt";
         cx = "Vào ô\nthứ ";
         cy = "Cất vào\nrương";
         cz = "Cất vào rương";
         cA = "Nói chuyện";
         cB = "Hụt";
         cC = "Cho";
         cD = "Nhận";
         cE = "Nhấn 2 lần";
         cF = "Có thể thu hoạch";
         cG = "Nhấn Y để đồng ý (";
         cH = "Nhấn # để đồng ý (";
         plsRestartGame = "Xin khởi động lại game để cập nhật dữ liệu";
         cJ = "Đang online";
         cK = "Đang offline";
         cL = "Kết bạn";
         cM = "Chat player";
         cN = "Chat với";
         cO = "Capsule cho bang";
         cP = "Capsule cá nhân";
         cQ = "Capsule bang";
         cR = "Cho đậu";
         cS = "Nhận đậu";
         cT = "Xin đậu";
         cU = " lần";
         cV = "Đã nhận";
         cW = "Sức mạnh";
         cX = "Ngày gia nhập";
         cY = "Bang chủ";
         cZ = "Phó bang";
         da = "Điểm sức mạnh";
         db = "Thành viên";
         dc = new String[]{"Thành", "viên"};
         dd = new String[]{"Chat", "bang"};
         de = new String[]{"Rời", "bang"};
         df = new String[]{"Lập", "bang"};
         dg = new String[]{"Tìm", "bang"};
         dh = new String[]{"Khẩu", "hiệu"};
         di = new String[]{"Biểu", "tượng"};
         dj = new String[]{"Xin", "đậu"};
         dk = "Cấp";
         dl = "Ngày thành lập: ";
         dm = "Danh sách bang";
         dn = "Chưa vào bang";
         fd_array_2 = new String[]{"Hiện tại bang chỉ có", " 1 thành viên là bạn.", " Xin chờ có người xin vào.", " Bạn có thể chọn vào nhân vật", " khác để mời họ vào bang"};
         dp = "Nhập tên bang";
         dq = "Tên bang";
         dr = "Chat bang";
         ds = "Nhập tên bang cần tạo";
         dt = "Nhập khẩu hiệu bang";
         du = "Bạn có muốn xin vào bang ";
         dv = "Chọn biểu tượng bang";
         dw = "Xin vào\nbang";
         dx = "Xem thành\nviên";
         dy = "Phong\nphó bang";
         dz = "Phong\nchủ bang";
         dA = "Cắt chức";
         dB = "Loại thành viên";
         dC = "Bạn hãy nhập tên bang";
         dD = "Bạn hãy nhập khẩu hiệu bang";
         dE = "Không tìm thấy bang";
         dF = "trước";
         dG = "Đang tìm bang";
         dH = "Giao dịch";
         dI = " chưa khóa giao dịch";
         dJ = "Chưa khóa giao dịch";
         dK = " đã khóa giao dịch";
         dL = "Đã khóa giao dịch";
         dM = "Khóa giao dịch";
         dN = "Chờ đối thủ khóa";
         dO = "Nhất nút \'Xong\'";
         dP = "Xong";
         dQ = "Đối phương";
         dR = "Bạn";
         dS = "Khóa";
         dT = "Số tiền giao dịch";
         dU = "Lấy ra";
         dV = "Bỏ ra";
         dW = "Sử dụng\ncho\nđệ tử";
         dX = "Bán";
         dY = "Nhập số tiền muốn giao dịch";
         dZ = "Nhập số tiền";
         ea = "Nhập sai số tiền, vui lòng nhập lại";
         eb = "Bạn không đủ tiền, vui lòng nhập lại";
         ec = "Nhập số lượng muốn giao dịch";
         ed = "Nhập số lượng";
         ee = "Nhập sai số lượng, vui lòng nhập lại";
         ef = "Đã có vật phẩm này";
         eg = "Vui lòng mở khóa trước khi sử dụng vật phẩm để giao dịch";
         eh = "gốc";
         ei = "cần";
         ej = "Cần";
         ek = "Miễn phí";
         el = "Chọn vật phẩm";
         em = "Bất kì";
         en = "Xin chào!";
         eo = "Cậu muốn mua gì?";
         ep = "Con muốn học gì?";
         eq = "Bạn có chắc muốn giao dịch với những vật phẩm trên không ?";
         er = "Học với";
         es = "Mua bằng";
         et = "Không thể thực hiện khi đang kiệt sức";
         eu = "Sử dụng\nđể\nkết hợp";
         ev = "Sử dụng\nđể\ngiao dịch";
         ew = "Bạn không đủ ngọc để chat kênh thế giới";
         ex = "Chat kênh thế giới (5 ngọc)";
         ey = " muốn giao dịch với bạn, bạn có đồng ý không ?";
         ez = "Bạn vừa nâng cấp ";
         eA = " sang cấp ";
         eB = "tiềm năng để học";
         eC = "Điểm tiềm năng";
         eD = "Điểm thành tích";
         eE = "tăng";
         eF = "Tăng";
         eG = "Bạn chỉ có ";
         eH = " điểm tiềm năng. Hãy luyện tập thêm để có đủ ";
         eI = "Bạn có muốn dùng ";
         eJ = " tiềm năng để tăng vào ";
         eK = " HP không?";
         eL = " KI không?";
         eM = " sức đánh không?";
         eN = " chí mạng không?";
         eO = "Khi có ";
         eP = " tiềm năng, bạn sẽ được nâng cấp miễn phí ";
         eQ = ". Ngoài ra bạn có thể mua Bí Kíp từ Urôn để học nhanh";
         eR = "HP";
         eS = "KI";
         eT = "Sức đánh";
         eU = "Giáp";
         eV = "Thể lực";
         eW = "Chí mạng";
         eX = "Cấp độ";
         eY = "KI tiêu hao: ";
         eZ = "Tốc độ";
         fa = "miligiây";
         fb = "Đã đạt cấp tối đa";
         fc = "Cấp kế cần ";
         fd = "tiềm năng";
         fe = "Chưa học";
         ff = "Để học cần ";
         fg = "Học";
         fh = "để tăng 20 HP gốc";
         fi = "để tăng 20 MP gốc";
         fj = "để tăng 1 sức mạnh gốc";
         fk = new String[][]{{"Gohan", "Krillin", "Yamcha"}, {"Ốc tiêu", "Pocollo", "Kami"}, {"Cađic", "Rađic", "Kakalot"}};
         if(Main.typeClient == 7) {
            fk = new String[][]{{"Hango", "Linkhi", "Chayam"}, {"Deden", "Cololo", "Mika"}, {"Tageve", "Ditra", "Rotkaka"}};
         }

         fl = "Địa điểm nhiệm vụ";
         fm = "Không có nhiệm vụ";
         fn = "Hoàn thành, thưởng ";
         fo = "Nhiệm vụ thành tích";
         fp = "Trang bị";
         fq = "Bạn muốn làm gì";
         ft = "Chọn nơi muốn đến";
         fr = "Chọn";
         fs = "Chọn";
         fu = "Chọn để ẩn chat thế giới";
         fv = "Chọn để hiện chat thế giới";
         gc = "Chơi mới";
         gd = "Chơi TK";
         gf = "Chưa đăng ký";
         return;
      case 1:
         nr_bo.j = "http://world.teamobi.com";
         nr_x.j = Main.loadImage("/mainImage/logo1E.png");
         a = "Delete account";
         b = "You bought many gems today. Let\'s try again tomorrow!";
         c = "When selling successfully, you will receive Ruby non Gem. Do you want to continue consign?";
         d = "Equip";
         e = "Unlock";
         f = "Collection book";
         g = "Not enough";
         h = "Function in maintenance.";
         av = "Are you sure you want to pick this item ?";
         i = "level";
         j = "Results lucky number";
         bP = "Who to choose";
         bO = "Notification";
         k = "Auto reborn";
         l = "Auto function";
         m = "Are you sure you fusion forever with your disciple? You will lost your disciple and all disciple\'s equip, all disciple\'s power will convert to your potential.";
         gh = "Fusion dance forever";
         gg = "Fusion dance";
         ge = "Please enter complete information";
         n = "Continue";
         s = "Go home";
         r = "Status";
         o = "Attack";
         p = "Protect";
         q = "Follow";
         t = "Disciple";
         gi = "Go to";
         u = "Connection lost. Please try again later";
         v = "Low graphics";
         w = "High graphics";
         fZ = "Download";
         ga = "Clear data";
         gb = "When game have data errors, you should delete data. After delete data, you have to download data to play game.";
         fY = "Cancel";
         fX = "Please download data to play";
         x = "Abracadabra...";
         A = "Congratulations my dear";
         y = "Better luck next time my dear";
         fW = "Do you want go to future now with 1 gem ?";
         fV = "Speed up";
         B = "Analog";
         C = "Analog";
         D = "Analog";
         fS = "Inventory Password ";
         fT = "Enter Security password";
         fU = "Security password must be 6 number.";
         fR = "Please enter your number phone or email ,then enter your password to create new account";
         fQ = "You will lost your account forever if you change to another account,do you agree ?";
         E = "Register to protect account";
         fP = "You must finish the mission find 6 star dragon ball to recharge";
         fO = "Forum and Buy more gems";
         z = "Buy more gems";
         fN = "No items to buy";
         fM = "Hold up to get more";
         fL = "Hold down to get more";
         fK = "Page";
         fJ = "Up top";
         fB = "Consign by\ngold";
         fC = "Consign by\ngem";
         fD = "Consign by gold";
         fE = "Consign by gem";
         fF = "Cancel\nconsign";
         fG = "Get\nmoney";
         fI = "Sold";
         fH = "Selling";
         fA = "Consign";
         fx = "Sound";
         fy = "Sound";
         fz = "No enemy";
         bH = "Rank";
         bI = "Active point";
         F = "Registering";
         G = "Sent message, please wait for confirmed message.";
         H = "Message can not be delivered. Please check your account and restart game.";
         dW = "User for\ndisciple";
         I = "Message delivered";
         J = "Can not send message";
         K = "Congratulation, you have just send predicted message successfully.";
         L = "Message sending failed.";
         M = "Password must be 6 characters length.";
         N = "Enter number for private password only.";
         O = "Enter private password";
         P = "Select account";
         Q = "You didn\'t enter you email or phone number.";
         R = "You didn\'t enter password";
         S = "Account name must be longer than 5 character";
         T = "Phone number is invalid. Please enter like these following form: 0912345678 or 84918765432";
         U = "Email is invalid. Please enter like these following form: yournamehere@yahoo.com or yournamehere@gmail.com";
         V = "Register\nnew\naccount";
         W = "Select\nserver";
         X = "Forget pwd";
         Y = "Password";
         var10000 = new String[]{"Didn\'t have account? Please", "choose register menu."};
         Z = "Message";
         aa = new String[]{"Message", ""};
         ab = "No message";
         ac = "Do you want to cancel account protection function ?";
         ad = "Please check your account information carefully to recover account, in case forgot password\n";
         ae = "Phone number";
         af = "Email";
         ag = "Acc";
         ah = "Pwd";
         ai = "To recover password, please visit website http://nrosuno.com/matkhau";
         aj = "Dragon Ball";
         ak = "Character";
         al = "Account";
         am = "Account server";
         an = "You didn\'t enter character name";
         ao = "Character name can not too short";
         ap = "Character name can not longer than 15 characters";
         aq = "Character need to change name";
         ar = "Character name";
         as = "Log in";
         at = "Log in";
         au = "Register";
         bn = "Revenge";
         aw = "Please wait";
         ax = "Connecting";
         ay = "Downloading ";
         az = "Error! please restart game.";
         aA = "Error!.";
         aB = "Lost connection ";
         aC = "Change zone";
         aD = "Select zone";
         aE = "Website\nforum";
         aF = "Server";
         var10000 = new String[]{"Inventory", "Skill", "Potential", "Info", "Equipment"};
         aG = new String[]{"", "People: ", "Hair: "};
         aH = new String[]{"Earth", "Namekian", "Saiyan"};
         if(Main.typeClient == 7) {
            aH = new String[]{"Earth dragon", "Green dragon", "Red dragon"};
         }

         aI = new String[]{"Challenge", "Practice", "PK", "Add friend", "Invite clan", "Recover", "Information", "Private chat", "Invite to clan", "Block invite to clan"};
         aJ = new String[][]{{"Quest", ""}, {"Inven-", "tory"}, {"Skill", ""}, {"Func-", "tion"}};
         aK = new String[][]{{"Quest", ""}, {"Inven-", "tory"}, {"Skill", ""}, {"Clan", ""}, {"Func-", "tion"}};
         aL = new String[][]{{"Dis-", "ciple"}, {"Status", ""}, {"Inven-", "tory"}};
         aM = new String[][]{{"Dis-", "ciple"}, {"Status", ""}};
         aN = new String[]{"Add\nkey Q", "Add\nkey W", "Add\nkey E", "", "", "", "", ""};
         aO = new String[]{"Add\nkey 7", "Add\nkey 8", "Add\nkey 9", "", "", "", "", ""};
         aP = "Your current attack skill didn\'t add points";
         aQ = "Out of Senzu Bean. Come back and harvest more";
         aR = "You are already in this zone";
         aS = new String[]{"Find ", " at ", " to receive quest.", "You now complete all quests of this version, please wait for upcoming version."};
         aT = new String[]{"Exhausted", "Wait", "Return home", "Revive\nnow\n(1 gem)"};
         var10000 = new String[]{"Map", "Quest", "Clan"};
         aU = new String[]{"Senzu Bean is used for recovering HP and KI immediately", "You can only keep 10 Senzu Beans belong with you. If you want to have more, ask from your clan\'s friend", "All skills can be learnt free at Kame-Sennin, when you have enough potential points", "You can not fly or use skill if out of KI", "Attack monsters with your clan\'s friend will bring more potential points than training alone", "Training with your friends at appropriate zone will brought more potential points than attack monsters", "When upgraded, Senzu Bean will recover more HP and KI", "Login daily to get free Gem", "Chicken drumsticks will recover 100% HP and KI. Tomato recover 100% KI. Carrot recover 100% HP", "Senzu Bean tree will ripe after a period, even though you are offline", "If you don\'t login in 3 days, you power will decrease because of your laziness", "Your strength will decrease when attack monster, but it will increase when you stop", "Out of Gem? Go find NPC Bora"};
         aV = "After join class, you can receive quest from Head Master";
         aW = "Serial number";
         aX = "Card\'s code";
         aY = "Pay Vina ,Mobi, Viettel, VTC";
         aZ = "Pay card";
         ba = "Please enter serial number";
         bb = "Please enter card\'s code";
         bc = "bil";
         bd = "mil";
         be = "Menu";
         bf = "Close";
         bg = "Clear";
         bh = "Continue";
         bi = "Use";
         bj = "Yes";
         bk = "No";
         bl = "Exit";
         bm = "Chat";
         bo = "OK";
         bp = "Remember";
         bq = "Accept";
         br = "Cancel";
         bs = "Select";
         bt = "Enter";
         bu = "Open link";
         bv = "New character";
         bw = "Back";
         bx = "Kill";
         by = "Kill boss";
         bz = "gold";
         bA = "gem";
         bB = "ruby";
         bC = "You PK point is ";
         bD = " attacks you";
         bE = "Not enough KI to use";
         bF = "You have received";
         bG = "You have learnt ";
         bJ = "Friend";
         bK = "Enemy";
         bL = "No friend";
         bM = "World chat";
         bN = "Change flag";
         bQ = "Option";
         bR = "Increase resolution (strong devices)";
         bS = "Decrease resolution (weak devices)";
         bT = "Server notice";
         bX = "Special aura";
         bY = "Power aura";
         bV = "Small screen";
         bU = "Big screen";
         bW = "Do you want to exit game to change screen size?";
         bZ = "Chest";
         ca = new String[]{"Chest", ""};
         cb = new String[]{"Inven-", "tory"};
         cc = new String[]{"Combine", ""};
         cd = new String[]{"Map", ""};
         ce = new String[]{"Give", "item"};
         cf = new String[]{"Receive", "item"};
         cg = new String[]{"Zone", ""};
         ch = "Zone";
         ci = "Map";
         cj = "Receive item";
         ck = "Receive";
         cl = "Receive All";
         cm = "Go to the flashing point on the map for quest";
         cn = "For Earth only\n";
         co = "For Namekian Only\n";
         cp = "For Saiyan Only\n";
         cq = "Power required";
         cr = "Your power";
         cs = "Used";
         ct = "place";
         cu = "Upgrade";
         cv = "Upgrading";
         cw = "Add\nShort cut";
         cx = "Into\nplace ";
         cy = "Move to\nchest";
         cz = "Move to\nchest";
         cA = "Chat";
         cB = "Miss";
         cC = "Donate";
         cD = "Receive";
         cE = "Double Tap";
         cF = "Can harvest";
         cG = "Press Y to accept (";
         cH = "Press # to accept (";
         plsRestartGame = "Please restart game to update data";
         cJ = "Online";
         cK = "Offline";
         cL = "Make friend";
         cM = "Chat player";
         cN = "Chat with";
         cO = "Capsule Donate";
         cP = "Personal Capsule";
         cQ = "Clan\'s Capsule";
         cR = "Give bean";
         cS = "Receive bean";
         cT = "Request bean";
         cU = " time";
         cV = "Received";
         cW = "Power";
         cX = "Join date";
         cY = "Clan Leader";
         cZ = "Clan coleader";
         da = "Power points";
         db = "Member";
         dc = new String[]{"Member", ""};
         dd = new String[]{"Chat", "clan"};
         de = new String[]{"Leave", "clan"};
         df = new String[]{"Create", "clan"};
         dg = new String[]{"Find", "clan"};
         dh = new String[]{"Slogan"};
         di = new String[]{"Icon"};
         dj = new String[]{"Request", "bean"};
         dk = "Level";
         dl = "Clan birthday";
         dm = "Clan list";
         dn = "Not joint clan";
         fd_array_2 = new String[]{"You are the only one", " member of this clan.", " Someone may request to join.", " You can select other players", " to invite them join clan"};
         dp = "Enter clan\'s name";
         dq = "Clan\'s name";
         dr = "Clan chat";
         ds = "Enter clan\'s name you want to create";
         dt = "Enter clan\'s slogan";
         du = "Do you want to join clan ";
         dv = "Select clan\'s icon";
         dw = "Request join\nclan";
         dx = "View clan\'s\nmember";
         dy = "Order\ncoleader";
         dz = "Order\nleader";
         dA = "Dismiss";
         dB = "Kick member";
         dC = "Please enter clan\'s name";
         dD = "Please enter clan\'s slogan";
         dE = "Can not find clan";
         dF = "ago";
         dG = "Finding clan";
         dH = "Trade";
         dI = " didn\'t lock transaction";
         dJ = "Transaction is not locked";
         dK = " locked transaction";
         dL = "Transaction is locked";
         dM = "Lock transaction";
         dN = "Wait opponent to lock transaction";
         dO = "Press \'Done\'";
         dP = "Done";
         dQ = "Opponent";
         dR = "You";
         dS = "Lock";
         dT = "Transaction amount";
         dU = "Move to Equipment";
         dV = "Remove";
         dX = "Sale";
         dY = "Enter money to trade";
         dZ = "Enter money";
         ea = "Enter wrong amount, please try again";
         eb = "Not enough money, please try again";
         ec = "Enter quantity you want to trade";
         ed = "Enter quantity";
         ee = "Enter wrong quantity, please try again";
         ef = "You already have this item";
         eg = "Please unlock before trade this item";
         eh = "Base";
         ei = "need";
         ej = "Need";
         ek = "Free";
         el = "Select item";
         em = "Random";
         en = "Hello!";
         eo = "What do you want to buy?";
         ep = "What do you want to lear?";
         eq = "Are you sure you want to trade with those items?";
         er = "Learn with";
         es = "Buy with";
         et = "You can not perform this action when dying";
         eu = "Use\nfor\ncombine";
         ev = "Use\nfor\ntrade";
         ew = "You don\'t have enough gem to chat on world channel";
         ex = "Chat on world channel (5 gems)";
         ey = " want to trade with you, do you accept?";
         ez = "You have just upgrade ";
         eA = " to ";
         eB = "potential pts";
         eC = "Potential points";
         eD = "Achievement point";
         eE = "increase";
         eF = "Increase";
         eG = "You only have ";
         eH = " potential pts. Let\'s practice more to earn ";
         eI = "Do you want to use ";
         eJ = " potential pts to add ";
         eK = " for HP?";
         eL = " for KI?";
         eM = " for attack?";
         eN = " for critical?";
         eO = "At ";
         eP = " potential points, you can upgrade for free ";
         eQ = ". Or see Uron to buy recipes faster.";
         eR = "HP";
         eS = "KI";
         eT = "Attack";
         eU = "Armor";
         eV = "Vitality";
         eW = "Critical";
         eX = "Level";
         eY = "KI consume: ";
         eZ = "Speed";
         fa = "millisecond";
         fb = "Maximum level reached";
         fc = "Next level required ";
         fd = "potential";
         fe = "Not learnt";
         ff = "Require ";
         fg = "Learn";
         fh = "to gain 20 HP";
         fi = "to gain 20 MP";
         fj = "to gain 1 power point";
         fk = new String[][]{{"Gohan", "Krillin", "Yamcha"}, {"Dende", "Piccolo", "Kami"}, {"Vegeta", "Raditz", "Kakarot"}};
         if(Main.typeClient == 7) {
            fk = new String[][]{{"Hango", "Linkhi", "Chayam"}, {"Deden", "Cololo", "Mika"}, {"Tageve", "Ditra", "Rotkaka"}};
         }

         fl = "Quest place";
         fm = "You don\'t have quest";
         fn = "Complete, reward ";
         fo = "Achievement quest";
         fp = "Equipment";
         fq = "What do you want to do";
         fr = "Select";
         fs = "Select";
         ft = "Select your destination";
         fu = "OK to disable World Channe";
         fv = "OK to enable world channel";
         gc = "New game";
         gd = "Play acc";
         gf = "Not register yet";
         return;
      case 2:
         nr_bo.j = "http://dragonball.indonaga.com";
         nr_x.j = Main.loadImage("/mainImage/logo1E.png");
         nr_bv.a();
      default:
      }
   }
}
